### ISSUE TITLE
Change the loading time

### ISSUE THREAD

**Issue by andrepaes** [meloalright/vue-ins-progress-bar#11]
Hello, i now that we can call the start and the finish of the loading bar but i need a smooth way to do that, i have to make some api calls and it isn't a fixed response time so i need to display that animation in a different time than default. How can i do that?
Thanks in advance,
André Luiz

**Comment by meloalright** [comment]
> Hello, i now that we can call the start and the finish of the loading bar but i need a smooth way to do that, i have to make some api calls and it isn't a fixed response time so i need to display that animation in a different time than default. How can i do that?
> Thanks in advance,
> André Luiz

em... maybe you just wanna make the fadeout animation smoothly? Maybe u just need to modify this [src/vue-ins-progress-bar.vue#L50-L51](https://github.com/meloalright/vue-ins-progress-bar/blob/master/src/vue-ins-progress-bar.vue#L50-L51) in your way @andrepaes
