### ISSUE TITLE
Not working on Vue3 CLI with TS

### ISSUE THREAD

**Issue by moshetanzer** [meloalright/vue-ins-progress-bar#15]
Hi,

I really love your progress bar, but have tried so many things and I just cannot get it to work.

This is the error I am getting in the console;

TypeError: Object is not a constructor

**Comment by meloalright** [comment]
yeah.. In Vue3 u can use the https://github.com/tangyouge/vue3-progress

**Comment by moshetanzer** [comment]
Have got it to work with Vue3 TS. Can I publish a new public repo?

**Comment by meloalright** [comment]
> Have got it to work with Vue3 TS. Can I publish a new public repo?

Great PR in vue3-progress!

I have replied to u in vue3-progress https://github.com/tangyouge/vue3-progress/issues/6

typed [vue3-progress@0.0.1-beta4](https://www.npmjs.com/package/vue3-progress/v/0.0.1-beta4) has published

**Comment by moshetanzer** [comment]
Added another PR to stop ESLINT error. Can you check it out. It is literally just ignore next line in example script. 

Best Regards
