### ISSUE TITLE
demo代码直接拷贝的，报错

### ISSUE THREAD

**Issue by shen-lan** [meloalright/vue-ins-progress-bar#3]
`webpack-internal:///./node_modules/core-js/modules/es6.promise.js:110 Unhandled promise rejection TypeError: Cannot read property 'finish' of undefined`

`TypeError: Cannot read property 'start' of undefined`

**Comment by shen-lan** [comment]
打扰了。是我把使用代码放在了main.js里路由拦截里去使用的原因。。。。
现在可以使用了。但是为什么和demo有点不一样呢？Demo里加载完毕会是绿色，但是我这里加载完毕不是绿色。。。。

**Comment by meloalright** [comment]
@shen-lan (´• ᵕ •`)* 啊居然颜色会出问题 有没有gif之类的来看下
