### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by Mohammed-Gaber** [meloalright/vue-ins-progress-bar#4]
i got this issue
![screenshot from 2018-09-29 23-10-35](https://user-images.githubusercontent.com/33400244/46250592-df1bf280-c43d-11e8-9aa1-4d570021dd8d.png)
but when i check the node modules i find every thing fine but it still returns 'undefined'
and when i run 
`npm install @types/vue-ins-progress-bar`
it returns
`npm ERR! code E404 
npm ERR! 404 Not Found: @types/vue-ins-progress-bar@latest
`

**Comment by meloalright** [comment]
@Mohammed-Gaber 

Yeah... That is a bug

You know There is no index.d.ts that contains the typings for the package

On the other hand, the modules has not been added into `@types`

**Comment by meloalright** [comment]
> i got this issue
> ![screenshot from 2018-09-29 23-10-35](https://user-images.githubusercontent.com/33400244/46250592-df1bf280-c43d-11e8-9aa1-4d570021dd8d.png)
> but when i check the node modules i find every thing fine but it still returns 'undefined'
> and when i run
> `npm install @types/vue-ins-progress-bar`
> it returns
> `npm ERR! code E404 npm ERR! 404 Not Found: @types/vue-ins-progress-bar@latest `

Hey ~ There's a good news, we just supported TypeScript    
   
```shell
$ npm i vue-ins-progress-bar@1.3.0
```

Just install latest version and use it   
This bug will not exist any longer @Mohammed-Gaber
