### ISSUE TITLE
除了height，还有其他可以改变样式的传参吗

### ISSUE THREAD

**Issue by Linkding** [meloalright/vue-ins-progress-bar#5]
如题

**Comment by meloalright** [comment]
> 如题

你好哈 期望改变哪些样式属性呢

**Comment by meloalright** [comment]
@Linkding

**Comment by Linkding** [comment]
比如color，毕竟不是所有ui风格都是ins这么炫的嘛

**Comment by meloalright** [comment]
> 比如color，毕竟不是所有ui风格都是ins这么炫的嘛

@Linkding 额 哈哈 那这个 package 岂不就不能叫 vue-ins-progress-bar 了 =。=

**Comment by meloalright** [comment]
> 比如color，毕竟不是所有ui风格都是ins这么炫的嘛

@Linkding 现阶段只支持 height 如果有更好的建议欢迎提交 PR 哈

**Comment by Linkding** [comment]
> > 比如color，毕竟不是所有ui风格都是ins这么炫的嘛
> 
> @Linkding 额 哈哈 那这个 package 岂不就不能叫 vue-ins-progress-bar 了 =。=

也对哈，那可以开发多个组件了，哈哈
