### ISSUE TITLE
IE 语法解析报错

### ISSUE THREAD

**Issue by gongsan9527** [meloalright/vue-ins-progress-bar#6]
script1003: 缺少 ':'

**Comment by meloalright** [comment]
> script1003: 缺少 ':'

你好 请问能否提供下所使用的的 IE 版本 和 Windows 版本？

**Comment by meloalright** [comment]
> script1003: 缺少 ':'


多亏 @tangyouge 的贡献 新版本的彩虹进度条 v1.1.7 发布到 npm 了 已经兼容了 IE~
```shell
$ npm i vue-ins-progress-bar@1.1.7
```
直接安装即可使用
可以参考 [Live Demo ? time=20190805](https://meloalright.github.io/vue-ins-progress-bar/?time=20190805) 在IE上的表现哟 @gongsan9527

**Comment by gongsan9527** [comment]
好！
