### ISSUE TITLE
IE兼容性有问题，可以调试一下吗

### ISSUE THREAD

**Issue by xuzhitudev** [meloalright/vue-ins-progress-bar#7]
IE兼容性有问题，可以调试一下吗

**Comment by meloalright** [comment]
> IE兼容性有问题，可以调试一下吗

你好 请问能否提供下所使用的的 IE 版本 和 Windows 版本？

**Comment by xuzhitudev** [comment]
你好 用的是Windows10、 IE9及以上版本吧，谢谢啦

发自我的 iPhone

**Comment by meloalright** [comment]
> 你好 用的是Windows10、 IE9及以上版本吧，谢谢啦 发自我的 iPhone
> […](#)
> 在 2019年7月27日，上午11:15，meloalright ***@***.***> 写道： IE兼容性有问题，可以调试一下吗 你好 请问能否提供下所使用的的 IE 版本 和 Windows 版本？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

多亏 @tangyouge 的贡献 新版本的彩虹进度条 v1.1.7 发布到 npm 了 已经兼容了 IE~
```shell
$ npm i vue-ins-progress-bar@1.1.7
```
直接安装即可使用
可以参考 [Live Demo ? time=20190805](https://meloalright.github.io/vue-ins-progress-bar/?time=20190805) 在IE上的表现哟 @patienceone
